# Site settings
title: Freyua || Xiaoyuan
description: personal page
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://freyua911.github.io/XiaoYuan.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Xiao Yuan
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title:Student in Electonic engineering & Interaction design
email: xy.freyua@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "https://freyua911.github.io/XiaoYuan.github.io/"

exclude: ['package.json', 'src' , 'node_modules']
